name: golangci-lint
on:
  pull_request:
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          only-new-issues: true
